name: Integration Test Sample App
on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    name: SDK Test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      # Execute integration tests
      - name: Integration Test
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 29
          profile: Nexus 6P
          cores: 4
          ram-size: 4096M
          heap-size: 2048M
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew :app:connectedandroidLibDebugAndroidTest
