name: Unit Test Neuroid
on:
  pull_request:
    branches:
      - develop
      - master

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build AAR
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name:  set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build AAR ⚙️🛠
        run: bash ./gradlew :NeuroID:assemble

  test:
    name: SDK Test
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name:  set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Execute unit test neuroid lib
      - name: Unit Test NeuroID
        run: ./gradlew :NeuroID:testAndroidLibDebugUnitTest `
