# ******************************************************************
# This workflow creates a Github release with the version in
# the version.properties file. The updated version is then available
# in https://jitpack.io/#neuro-id/neuroid-android-sdk
# ******************************************************************

name: Release Android SDK

on:
  push:
    branches:
      - main
    paths:
      - version.properties

env:
  ACTION_URL: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'

jobs:
  publish:
    name: Publishing SDK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Cache Gradle and wrapper
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Get Version and Grant Permission for Gradlew
        run: |
          chmod +x gradlew
          echo "TAG=$(grep '^SDK_VERSION=' version.properties | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Build AAR ⚙️🛠
        run: bash ./gradlew :NeuroID:assemble

      - name: Create Release and upload assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ env.TAG }}" \
            NeuroID/build/outputs/aar/androidLib/neuro-id-android-sdk-androidLib-${{ env.TAG }}-release.aar#neuro-id-android-sdk-androidLib-${{ env.TAG }}-release \
            NeuroID/build/outputs/aar/reactNativeLib/neuro-id-android-sdk-reactNativeLib-${{ env.TAG }}-release.aar#neuro-id-android-sdk-reactNativeLib-${{ env.TAG }}-release \
            NeuroID/build/outputs/aar/androidLib/neuro-id-android-sdk-androidLib-${{ env.TAG }}-debug.aar#neuro-id-android-sdk-androidLib-${{ env.TAG }}-debug \
            NeuroID/build/outputs/aar/reactNativeLib/neuro-id-android-sdk-reactNativeLib-${{ env.TAG }}-debug.aar#neuro-id-android-sdk-reactNativeLib-${{ env.TAG }}-debug \
            --latest \
            --title "${{ env.TAG }}" \
            --notes 'The NeuroID Android SDK (${{ env.TAG }}) is now available.' \
            --generate-notes

      - name: Send Release Succeeded Result to NID Mobile Infra Repo
        if: success()
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GPR_API_KEY }}" \
            https://api.github.com/repos/Neuro-ID/neuroid-mobile-infra/dispatches \
            -d '{"event_type":"release","client_payload":{"status":"success", "service": "android", "version": "${{ env.TAG }}", "action_url": "${{ env.ACTION_URL }}"}}'

      - name: Send Release Failure Result to NID Mobile Infra Repo
        if: failure()
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GPR_API_KEY }}" \
            https://api.github.com/repos/Neuro-ID/neuroid-mobile-infra/dispatches \
            -d '{"event_type":"release","client_payload":{"status":"failure", "service": "android", "version": "${{ env.TAG }}", "action_url": "${{ env.ACTION_URL }}"}}'
