package com.neuroid.tracker.models


data class NIDEventSessionModel(
    val type: String,
    val f: String,
    val siteId: String,
    val sid: String,
    val lsid: String,
    val cid: String,
    val did: String,
    val iid: String,
    val loc: String,
    val ua: String,
    val tzo: Int,
    val lng: String,
    val ce: Boolean,
    val je: Boolean,
    val ol: Boolean,
    val p: String,
    val sh: Int,
    val sw: Int,
    val ah: Int,
    val aw: Int,
    val cd: Int,
    val pd: Int,
    val jsl: List<String>?,
    val dnt: Boolean,
    val url: String,
    val ns: String,
    val jsv: String,
    val idls: Long,
    val ts: Long,
)
